version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - '4566:4566' 
      - '4510-4559:4510-4559' 
    volumes:
      - localstack_data:/tmp/localstack

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=1
      - AWS_SECRET_ACCESS_KEY=1
      - REGION=us-east-1
      - TEST_QUEUE=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/localstack-queue
    ports:
      - '3000:3000'
    depends_on:
      - localstack

volumes:
  localstack_data:
